import os
from dotenv import load_dotenv

load_dotenv()

AZURE_PROMPT_FLOW_RAG_ENDPOINT = os.getenv("AZURE_PROMPT_FLOW_RAG_ENDPOINT")
AZURE_PROMPT_FLOW_RAG_DEPLOYMENT_NAME = os.getenv("AZURE_PROMPT_FLOW_RAG_DEPLOYMENT_NAME")
AZURE_PROMPT_FLOW_RAG_API_KEY = os.getenv("AZURE_PROMPT_FLOW_RAG_API_KEY")